"""Backward-compatible re-exports. Import from sub-modules directly."""

from .app import Dashboard
from .cli import main
from .config import PROJECT_ROOT, USER_PREFS_FILENAME, DashboardConfig
from .helpers import (
    WEBHOOK_SIGNAL_FILE,
    ServiceInfo,
    check_webhook_signal,
    detect_affected_services,
    detect_native_processes,
    detect_prod_mode,
    find_config,
    format_uptime,
    get_base_url,
    get_changed_files,
    get_compose_cmd,
    get_compose_file,
    get_current_ref,
    get_data_freshness,
    get_error_counts,
    get_git_info,
    get_git_refs,
    get_git_status_summary,
    parse_all_containers,
    parse_services,
)
from .widgets import LinksPanel, ServicePanel, UpdateBanner, WebhookBanner

__all__ = [
    "Dashboard",
    "DashboardConfig",
    "LinksPanel",
    "PROJECT_ROOT",
    "ServiceInfo",
    "ServicePanel",
    "USER_PREFS_FILENAME",
    "UpdateBanner",
    "WEBHOOK_SIGNAL_FILE",
    "WebhookBanner",
    "check_webhook_signal",
    "detect_affected_services",
    "detect_native_processes",
    "detect_prod_mode",
    "find_config",
    "format_uptime",
    "get_base_url",
    "get_changed_files",
    "get_compose_cmd",
    "get_compose_file",
    "get_current_ref",
    "get_data_freshness",
    "get_error_counts",
    "get_git_info",
    "get_git_refs",
    "get_git_status_summary",
    "main",
    "parse_all_containers",
    "parse_services",
]
